### ISSUE TITLE
Improve a11y

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1206]
Improve accessibility:
- [x] ~~select~~ #1517, #1465 PR - #1594 
- [x] ~~attach~~ #1491 PR - #1575 
- [x] ~~button~~ #1479 PR - #1553
- [x] ~~checkbox~~ #1492 PR - #1558
- [x] ~~checkbox-group~~ #1521 PR - #1558 
- [x] ~~control-group~~ #1522 PR #1556
- [x] ~~control~~
- [x] ~~dropdown~~ #1501 PR - #1636 
- [x] ~~icon~~
- [x] ~~image~~ #1488 PR - #1554
- [x] ~~input~~ #1504
- [x] ~~link~~ #1476 PR - #1555
- [x] ~~menu, menu-item~~ #1508, #1458 PR - #1578
- [x] ~~modal~~ #1509, #1459 PR - #1580 
- [x] ~~popup~~ #1510, #1460 PR - #1579
- [x] ~~progressbar~~ #1511 PR - #1572
- [x] ~~radio, radio-group~~ #1512 PR - #1557 
- [x] ~~spin~~ #1537
- [x] ~~textarea~~ #1515
- [x] ~~z-index-group~~

All listed components (except crossed out items) must be accessible to assistive technologies (AT). We use JAWS for testing as the most popular AT.

**Test scope**: [Firefox](https://www.mozilla.org/en-US/firefox/new/) + [JAWS (40-min trial)](http://www.freedomscientific.com/Downloads/JAWS)

**Virtualization**: [VirtualBox](https://www.virtualbox.org/wiki/Downloads) + [MS Windows](http://dev.modern.ie/tools/vms/#downloads) (for Mac or Linux users)

[WAI-ARIA specification](http://www.w3.org/TR/wai-aria/)

Old main PR #1380 (won't be merged, look for some solutions)

Notes:
- item checked mean that PR was sent
- crossed oud items - PR already merged

**Comment by aristov** [comment]
Summary from meeting with @ruslansagitov:
1. get rid of public API for a11y
2. get rid of duplicate attributes
3. make test form and look how it works
4. examine complex cases (such as `radio_type_button`, `checkbox-group`, `menu` etc.)

UPD: comment is outdated, look issue description for details.
