### ISSUE TITLE
Refact ENB config

### ISSUE THREAD

**Issue by blond** [bem/bem-components#1345]
- [ ] Add config
- [ ] Add helper for page configure (#1421)
- [x] Add helper for ENB techs (#1420)
- [ ] Move tasks into separate configs (#1419)
- [ ] Move dist into separate config (#1418)
- [x] Use autoprefixer with `enb-stylus/css-stylus-with-autoprefixer` tech (#1417)
- [x] Use `borschik` for js (#1416)
- [ ] Should not add template engines to target with browser JavaScript (#1429)

**Comment by qfox** [comment]
`v2` only?

**Comment by tadatuta** [comment]
@zxqfox yes, there's no `v3` yet ;)

**Comment by qfox** [comment]
@tadatuta _oopsie_ We should make it asap! ;-)

What you think about making enb config as close as possible to build flow?

**upd**
Also I feel like enb-tech libraries (or new modular system tech libraries) should make a manifest or something-like with information about techs they contains. It makes possible to have a registry with all available techs, their functionality, their configs, etc.
As well as block libraries btw.

**Comment by Guria** [comment]
I'm waiting for this to be finished. It would be very helpful as reference for  own library of components.

**Comment by Guria** [comment]
@blond  #1420 could be marked as checked on list
is there any ETA on this task?

**Comment by blond** [comment]
> could be marked as checked on list

Thanks, fixed.

> is there any ETA on this task?

no :(

**Comment by Guria** [comment]
remove js-js build step
